# **Electric Vehicle Charge and Range Analysis**

In [ ]:
import pandas as pd

evindia = pd.read_csv("EVIndia.csv")
charging = pd.read_csv("electric_vehicle_charging_station_list.csv")
electric_clean = pd.read_csv("ElectricCarData_Clean.csv")
cheapest = pd.read_csv("Cheapestelectriccars-EVDatabase.csv")

In [ ]:
evindia.info()
evindia.describe()
evindia.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Car                12 non-null     object
 1   Style              12 non-null     object
 2   Range              12 non-null     object
 3   Transmission       12 non-null     object
 4   VehicleType        12 non-null     object
 5   PriceRange(Lakhs)  12 non-null     float64
 6   Capacity           12 non-null     object
 7   BootSpace          12 non-null     object
 8   BaseModel          12 non-null     object
 9   TopModel           12 non-null     object
dtypes: float64(1), object(9)
memory usage: 1.1+ KB

Car                  0
Style                0
Range                0
Transmission         0
VehicleType          0
PriceRange(Lakhs)    0
Capacity             0
BootSpace            0
BaseModel            0
TopModel             0
dtype: int64

In [ ]:
evindia.duplicated().sum()
charging.duplicated().sum()
electric_clean.duplicated().sum()
cheapest.duplicated().sum()

np.int64(0)

In [ ]:
electric_clean["Range_Km"].describe()

count    103.000000
mean     338.786408
std      126.014444
min       95.000000
25%      250.000000
50%      340.000000
75%      400.000000
max      970.000000
Name: Range_Km, dtype: float64

In [ ]:
cheapest["PriceinGermany"] = cheapest["PriceinGermany"].replace('[€,]', '', regex=True)
cheapest["PriceinGermany"] = cheapest["PriceinGermany"].astype(float)

In [ ]:
cheapest["Range"] = pd.to_numeric(cheapest["Range"], errors='coerce')

In [ ]:
evindia = evindia.drop_duplicates()

In [ ]:
evindia.to_csv("EVIndia_cleaned.csv", index=False)
charging.to_csv("Charging_cleaned.csv", index=False)
electric_clean.to_csv("ElectricCar_cleaned.csv", index=False)
cheapest.to_csv("CheapestEV_cleaned.csv", index=False)

In [ ]:
evindia_new = pd.read_csv("EVIndia_cleaned.csv")
charging_new = pd.read_csv("Charging_cleaned.csv")
electric_clean_new = pd.read_csv("ElectricCar_cleaned.csv")
cheapest_new = pd.read_csv("CheapestEV_cleaned.csv")

In [ ]:
evindia_new.info()
evindia_new.isnull().sum()
evindia_new.duplicated().sum()
evindia_new.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Car                12 non-null     object
 1   Style              12 non-null     object
 2   Range              12 non-null     object
 3   Transmission       12 non-null     object
 4   VehicleType        12 non-null     object
 5   PriceRange(Lakhs)  12 non-null     float64
 6   Capacity           12 non-null     object
 7   BootSpace          12 non-null     object
 8   BaseModel          12 non-null     object
 9   TopModel           12 non-null     object
dtypes: float64(1), object(9)
memory usage: 1.1+ KB

       PriceRange(Lakhs)
count          12.000000
mean           75.524167
std            59.975546
min            13.640000
25%            22.795000
50%            64.575000
75%           116.750000
max           180.000000

In [ ]:
charging_new.info()
charging_new.isnull().sum()
charging_new.duplicated().sum()
charging_new.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 202 entries, 0 to 201
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   region      202 non-null    object
 1   address     202 non-null    object
 2   aux addres  202 non-null    object
 3   latitude    202 non-null    float64
 4   longitude   202 non-null    float64
 5   type        202 non-null    object
 6   power       202 non-null    object
 7   service     202 non-null    object
dtypes: float64(2), object(6)
memory usage: 12.8+ KB

         latitude   longitude
count  202.000000  202.000000
mean    25.960987   78.418002
std      5.616108    3.097664
min      8.481051   76.277781
25%     28.535516   77.212996
50%     28.580286   77.226252
75%     28.617783   77.375216
max     28.642892   88.509064

In [ ]:
electric_clean_new.info()
electric_clean_new.isnull().sum()
electric_clean_new.duplicated().sum()
electric_clean_new.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103 entries, 0 to 102
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Brand            103 non-null    object
 1   Model            103 non-null    object
 2   AccelSec         103 non-null    float64
 3   TopSpeed_KmH     103 non-null    int64
 4   Range_Km         103 non-null    int64
 5   Efficiency_WhKm  103 non-null    int64
 6   FastCharge_KmH   103 non-null    object
 7   RapidCharge      103 non-null    object
 8   PowerTrain       103 non-null    object
 9   PlugType         103 non-null    object
 10  BodyStyle        103 non-null    object
 11  Segment          103 non-null    object
 12  Seats            103 non-null    int64
 13  PriceEuro        103 non-null    int64
dtypes: float64(1), int64(5), object(8)
memory usage: 11.4+ KB

,AccelSec,TopSpeed_KmH,Range_Km,Efficiency_WhKm,Seats,PriceEuro
count,103.000000,103.000000,103.000000,103.000000,103.000000,103.000000
mean,7.396117,179.194175,338.786408,189.165049,4.883495,55811.563107
std,3.017430,43.573030,126.014444,29.566839,0.795834,34134.665280
min,2.100000,123.000000,95.000000,104.000000,2.000000,20129.000000
25%,5.100000,150.000000,250.000000,168.000000,5.000000,34429.500000
50%,7.300000,160.000000,340.000000,180.000000,5.000000,45000.000000
75%,9.000000,200.000000,400.000000,203.000000,5.000000,65000.000000
max,22.400000,410.000000,970.000000,273.000000,7.000000,215000.000000

In [ ]:
cheapest_new.info()
cheapest_new.isnull().sum()
cheapest_new.duplicated().sum()
cheapest_new.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             180 non-null    object
 1   Subtitle         180 non-null    object
 2   Acceleration     180 non-null    object
 3   TopSpeed         180 non-null    object
 4   Range            0 non-null      float64
 5   Efficiency       180 non-null    object
 6   FastChargeSpeed  180 non-null    object
 7   Drive            180 non-null    object
 8   NumberofSeats    180 non-null    int64
 9   PriceinGermany   168 non-null    float64
 10  PriceinUK        136 non-null    object
dtypes: float64(2), int64(1), object(8)
memory usage: 15.6+ KB

       Range  NumberofSeats  PriceinGermany
count    0.0     180.000000      168.000000
mean     NaN       5.166667    58725.386905
std      NaN       0.971666    32721.260340
min      NaN       2.000000    18460.000000
25%      NaN       5.000000    38000.000000
50%      NaN       5.000000    50647.500000
75%      NaN       5.000000    64647.500000
max      NaN       7.000000   215000.000000

In [ ]:
cheapest_new["Range"] = cheapest_new["Range"].astype(str)
cheapest_new["Range"] = cheapest_new["Range"].str.replace(" km","")
cheapest_new["Range"] = pd.to_numeric(cheapest_new["Range"], errors='coerce')

In [ ]:
cheapest_new["PriceinUK"] = cheapest_new["PriceinUK"].str.replace("£","")
cheapest_new["PriceinUK"] = cheapest_new["PriceinUK"].str.replace(",","")
cheapest_new["PriceinUK"] = pd.to_numeric(cheapest_new["PriceinUK"], errors='coerce')

In [ ]:
cheapest_new.isnull().sum()
cheapest_new.describe()

       Range  NumberofSeats  PriceinGermany      PriceinUK
count    0.0     180.000000      168.000000     136.000000
mean     NaN       5.166667    58725.386905   52939.058824
std      NaN       0.971666    32721.260340   28667.678844
min      NaN       2.000000    18460.000000   19200.000000
25%      NaN       5.000000    38000.000000   31500.000000
50%      NaN       5.000000    50647.500000   45000.000000
75%      NaN       5.000000    64647.500000   64227.500000
max      NaN       7.000000   215000.000000  189000.000000

In [ ]:
cheapest_new.columns

Index(['Name', 'Subtitle', 'Acceleration', 'TopSpeed', 'Range', 'Efficiency',
       'FastChargeSpeed', 'Drive', 'NumberofSeats', 'PriceinGermany',
       'PriceinUK'],
      dtype='object')

In [ ]:
cheapest_new.head(5)

,Name,Subtitle,Acceleration,TopSpeed,Range,Efficiency,FastChargeSpeed,Drive,NumberofSeats,PriceinGermany,PriceinUK
0,Opel Ampera-e,Battery Electric Vehicle | 58 kWh,7.3 sec,150 km/h,NaN,173 Wh/km,210 km/h,Front Wheel Drive,5,42990.0,NaN
1,Renault Kangoo Maxi ZE 33,Battery Electric Vehicle | 31 kWh,22.4 sec,130 km/h,NaN,194 Wh/km,-,Front Wheel Drive,5,NaN,31680.0
2,Nissan Leaf,Battery Electric Vehicle | 36 kWh,7.9 sec,144 km/h,NaN,164 Wh/km,230 km/h,Front Wheel Drive,5,29990.0,25995.0
3,Audi e-tron Sportback 55 quattro,Battery Electric Vehicle | 86.5 kWh,5.7 sec,200 km/h,NaN,231 Wh/km,600 km/h,All Wheel Drive,5,NaN,79900.0
4,Porsche Taycan Turbo S,Battery Electric Vehicle | 83.7 kWh,2.8 sec,260 km/h,NaN,215 Wh/km,860 km/h,All Wheel Drive,4,186336.0,138830.0

In [ ]:
cheapest_new = cheapest_new.drop(columns=["Range"])

In [ ]:
cheapest_new["Acceleration"] = cheapest_new["Acceleration"].str.replace(" sec","")
cheapest_new["Acceleration"] = pd.to_numeric(cheapest_new["Acceleration"], errors='coerce')

cheapest_new["TopSpeed"] = cheapest_new["TopSpeed"].str.replace(" km/h","")
cheapest_new["TopSpeed"] = pd.to_numeric(cheapest_new["TopSpeed"], errors='coerce')

cheapest_new["Efficiency"] = cheapest_new["Efficiency"].str.replace(" Wh/km","")
cheapest_new["Efficiency"] = pd.to_numeric(cheapest_new["Efficiency"], errors='coerce')

cheapest_new["FastChargeSpeed"] = cheapest_new["FastChargeSpeed"].str.replace(" km/h","")
cheapest_new["FastChargeSpeed"] = pd.to_numeric(cheapest_new["FastChargeSpeed"], errors='coerce')

In [ ]:
cheapest_new.info()
cheapest_new.isnull().sum()
cheapest_new.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             180 non-null    object
 1   Subtitle         180 non-null    object
 2   Acceleration     180 non-null    float64
 3   TopSpeed         180 non-null    int64
 4   Efficiency       180 non-null    int64
 5   FastChargeSpeed  175 non-null    float64
 6   Drive            180 non-null    object
 7   NumberofSeats    180 non-null    int64
 8   PriceinGermany   168 non-null    float64
 9   PriceinUK        136 non-null    float64
dtypes: float64(4), int64(3), object(3)
memory usage: 14.2+ KB

,Acceleration,TopSpeed,Efficiency,FastChargeSpeed,NumberofSeats,PriceinGermany,PriceinUK
count,180.000000,180.000000,180.000000,175.000000,180.000000,168.000000,136.000000
mean,7.854444,176.400000,194.272222,481.257143,5.166667,58725.386905,52939.058824
std,3.169465,42.096006,32.684001,242.744407,0.971666,32721.260340,28667.678844
min,2.100000,123.000000,104.000000,120.000000,2.000000,18460.000000,19200.000000
25%,5.575000,150.000000,168.000000,290.000000,5.000000,38000.000000,31500.000000
50%,7.500000,160.000000,188.500000,430.000000,5.000000,50647.500000,45000.000000
75%,9.625000,200.000000,215.250000,595.000000,5.000000,64647.500000,64227.500000
max,22.400000,410.000000,281.000000,1410.000000,7.000000,215000.000000,189000.000000

In [ ]:
evindia_new.to_csv("EVIndia_cleaned.csv", index=False)
charging_new.to_csv("Charging_cleaned.csv", index=False)
electric_clean_new.to_csv("ElectricCar_cleaned.csv", index=False)
cheapest_new.to_csv("CheapestEV_cleaned.csv", index=False)

In [ ]:
evindia_n = pd.read_csv("EVIndia_cleaned.csv")
charging_n = pd.read_csv("Charging_cleaned.csv")
electric_clean_n = pd.read_csv("ElectricCar_cleaned.csv")
cheapest_n = pd.read_csv("CheapestEV_cleaned.csv")

In [ ]:
evindia_new.info()
evindia_new.isnull().sum()
evindia_new.duplicated().sum()
evindia_new.describe()
charging_new.info()
charging_new.isnull().sum()
charging_new.duplicated().sum()
charging_new.describe()
electric_clean_new.info()
electric_clean_new.isnull().sum()
electric_clean_new.duplicated().sum()
electric_clean_new.describe()
cheapest_new.info()
cheapest_new.isnull().sum()
cheapest_new.duplicated().sum()
cheapest_new.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Car                12 non-null     object
 1   Style              12 non-null     object
 2   Range              12 non-null     object
 3   Transmission       12 non-null     object
 4   VehicleType        12 non-null     object
 5   PriceRange(Lakhs)  12 non-null     float64
 6   Capacity           12 non-null     object
 7   BootSpace          12 non-null     object
 8   BaseModel          12 non-null     object
 9   TopModel           12 non-null     object
dtypes: float64(1), object(9)
memory usage: 1.1+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 202 entries, 0 to 201
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   region      202 non-null    object
 1   address     202 non-null    object
 2   aux addres  202 non-null    object
 3   latitude    202 non-null    float64
 4   longitude   202 non-null    float64
 5   type        202 non-null    object
 6   power       202 non-null    object
 7   service     202 non-null    object
dtypes: float64(2), object(6)
memory usage: 12.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103 entries, 0 to 102
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Brand            103 non-null    object
 1   Model            103 non-null    object
 2   AccelSec         103 non-null    float64
 3   TopSpeed_KmH     103 non-null    int64
 4   Range_Km         103 non-null    int64
 5   Efficiency_WhKm  103 non-null    int64
 6   FastCharge_KmH   103 non-null    object
 7   RapidCharge      103 non-null    object
 8   PowerTrain       103 non-null    object
 9   PlugType         103 non-null    object
 10  BodyStyle        103 non-null    object
 11  Segment          103 non-null    object
 12  Seats            103 non-null    int64
 13  PriceEuro        103 non-null    int64
dtypes: float64(1), int64(5), object(8)
memory usage: 11.4+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             180 non-null    object
 1   Subtitle         180 non-null    object
 2   Acceleration     180 non-null    float64
 3   TopSpeed         180 non-null    int64
 4   Efficiency       180 non-null    int64
 5   FastChargeSpeed  175 non-null    float64
 6   Drive            180 non-null    object
 7   NumberofSeats    180 non-null    int64
 8   PriceinGermany   168 non-null    float64
 9   PriceinUK        136 non-null    float64
dtypes: float64(4), int64(3), object(3)
memory usage: 14.2+ KB

,Acceleration,TopSpeed,Efficiency,FastChargeSpeed,NumberofSeats,PriceinGermany,PriceinUK
count,180.000000,180.000000,180.000000,175.000000,180.000000,168.000000,136.000000
mean,7.854444,176.400000,194.272222,481.257143,5.166667,58725.386905,52939.058824
std,3.169465,42.096006,32.684001,242.744407,0.971666,32721.260340,28667.678844
min,2.100000,123.000000,104.000000,120.000000,2.000000,18460.000000,19200.000000
25%,5.575000,150.000000,168.000000,290.000000,5.000000,38000.000000,31500.000000
50%,7.500000,160.000000,188.500000,430.000000,5.000000,50647.500000,45000.000000
75%,9.625000,200.000000,215.250000,595.000000,5.000000,64647.500000,64227.500000
max,22.400000,410.000000,281.000000,1410.000000,7.000000,215000.000000,189000.000000